enum Opcodes6502
{
	ADC_IMMEDIATE			= 0x69,	//Add Memory to Accumulator with Carry
	ADC_ZEROPAGE			= 0x65,
	ADC_ZEROPAGE_X			= 0x75,
	ADC_ABSOLUTE_X			= 0x7D,
	ADC_ABSOLUTE_Y			= 0x79,
	ADC_PREINDEXED_INDIRECT	= 0x61,
	ADC_POSTINDEXED_INDIRECT= 0x71,
	AND_IMMEDIATE			= 0x29,	//"AND" Memory with Accumulator
	AND_ZEROPAGE			= 0x25,
	AND_ZEROPAGE_X			= 0x35,
	AND_ABSOLUTE			= 0x2D,
	AND_ABSOLUTE_X			= 0x3D,
	AND_ABSOLUTE_Y			= 0x39,
	AND_PREINDEXED_INDIRECT	= 0x21,
	AND_POSTINDEXED_INDIRECT= 0x31,
	ASL_ACCUMULATOR			= 0x0A,	//Shift Left One Bit (Memory or Accumulator)
	ASL_ZEROPAGE			= 0x06,
	ASL_ZEROPAGE_X			= 0x16,
	ASL_ABSOLUTE			= 0x0E,
	ASL_ABSOLUTE_X			= 0x1E,
	BCC 					= 0x90,	//Branch on Carry Clear
	BCS 					= 0xB0,	//Branch on Carry Set
	BEQ 					= 0xF0,	//Branch on Result Zero
	BIT_ZEROPAGE			= 0x24,	//Test Bits in Memory with Accumulator
	BIT_ABSOLUTE			= 0x2C,
	BMI 					= 0x30,	//Branch on Result Minus
	BNE 					= 0xD0,	//Branch on Result not Zero
	BPL 					= 0x10,	//Branch on Result Plus
	BRK 					= 0x00,	//Force Break
	BVC 					= 0x50,	//Branch on Overflow Clear
	BVS 					= 0x70,	//Branch on Overflow Set
	CLC 					= 0x18,	//Clear Carry Flag
	CLD 					= 0xD8,	//Clear Decimal Mode
	CLI 					= 0x58,	//Clear interrupt Disable Bit
	CLV 					= 0xB8,	//Clear Overflow Flag
	CMP_IMMEDIATE			= 0xC9,	//Compare Memory and Accumulator
	CMP_ZEROPAGE			= 0xC5,
	CMP_ZEROPAGE_X			= 0xD5,
	CMP_ABSOLUTE			= 0xCD,
	CMP_ABSOLUTE_X			= 0xDD,
	CMP_ABSOLUTE_Y			= 0xD9,
	CMP_PREINDEXED_INDIRECT	= 0xC1,
	CMP_POSTINDEXED_INDIRECT= 0xD1,
	CPX_IMMEDIATE			= 0xE0,	//Compare Memory and Index X
	CPX_ZEROPAGE			= 0xE4,
	CPX_ABSOLUTE 			= 0xEC,
	CPY_IMMEDIATE			= 0xC0,	//Compare Memory and Index Y
	CPY_ZEROPAGE			= 0xC4,
	CPY_ABSOLUTE			= 0xCC,
	DEC_ZEROPAGE			= 0xC6,	//Decrement Memory by One
	DEC_ZEROPAGE_X			= 0xD6,
	DEC_ABSOLUTE			= 0xCE,
	DEC_ABSOLUTE_X			= 0xDE,
	DEX						= 0xCA,	//Decrement Index X by One
	DEY						= 0x88,	//Decrement Index Y by One
	EOR_IMMEDIATE			= 0x49,	//"Exclusive-Or" Memory with Accumulator
	EOR_ZEROPAGE			= 0x45,
	EOR_ZEROPAGE_X			= 0x55,
	EOR_ABSOLUTE			= 0x40,
	EOR_ABSOLUTE_X			= 0x5D,
	EOR_ABSOLUTE_Y			= 0x59,
	EOR_PREINDEXED_INDIRECT	= 0x41,
	EOR_POSTINDEXED_INDIRECT= 0x51,
	INC_ZEROPAGE			= 0xE6,	//Increment Memory by One
	INC_ZEROPAGE_X 			= 0xF6,
	INC_ABSOLUTE 			= 0xEE,
	INC_ABSOLUTE_X 			= 0xFE,
	INX 					= 0xE8,	//Increment Index X by One
	INY 					= 0xC8,	//Increment Index Y by One
	JMP_ABSOLUTE 			= 0x4C,	//Jump to New Location
	JMP_INDIRECT 			= 0x6C,
	JSR 					= 0x20,	//Jump to New Location Saving Return Address
	LDA_IMMEDIATE			= 0xA9,	//Load Accumulator with Memory
	LDA_ZEROPAGE			= 0xA5,
	LDA_ZEROPAGE_X			= 0xB5,
	LDA_ABSOLUTE			= 0xAD,
	LDA_ABSOLUTE_X			= 0xBD,
	LDA_ABSOLUTE_Y			= 0xB9,
	LDA_PREINDEXED_INDIRECT	= 0xA1,
	LDA_POSTINDEXED_INDIRECT= 0xB1,
	LDX_IMMEDIATE			= 0xA2,	//Load Index X with Memory
	LDX_ZEROPAGE			= 0xA6,
	LDX_ZEROPAGE_Y			= 0xB6,
	LDX_ABSOLUTE			= 0xAE,
	LDX_ABSOLUTE_Y			= 0xBE,
	LDY_IMMEDIATE			= 0xA0,	//Load Index Y with Memory
	LDY_ZEROPAGE			= 0xA4,
	LDY_ZEROPAGE_X			= 0xB4,
	LDY_ABSOLUTE			= 0xAC,
	LDY_ABSOLUTE_X			= 0xBC,
	LSR_ACCUMULATOR 		= 0x4A,	//Shift Right One Bit (Memory or Accumulator)
	LSR_ZEROPAGE			= 0x46,
	LSR_ZEROPAGE_X			= 0x56,
	LSR_ABSOLUTE			= 0x4E,
	LSR_ABSOLUTE_X			= 0x5E,
	NOP 					= 0xEA,	//No Operation
	ORA_IMMEDIATE 			= 0x09,	//"OR" Memory with Accumulator
	ORA_ZEROPAGE			= 0x05,
	ORA_ZEROPAGE_X			= 0x15,
	ORA_ABSOLUTE			= 0x0D,
	ORA_ABSOLUTE_X			= 0x10,
	ORA_ABSOLUTE_Y			= 0x19,
	ORA_PREINDEXED_INDIRECT	= 0x01,
	ORA_POSTINDEXED_INDIRECT= 0x11,
	PHA 					= 0x48,	//Push Accumulator on Stack
	PHP 					= 0x08,	//Push Processor Status on Stack
	PLA 					= 0x68,	//Pull Accumulator from Stack
	PLP 					= 0x28,	//Pull Processor Status from Stack
	ROL_ACCUMULATOR 		= 0x2A,	//Rotate One Bit Left (Memory or Accumulator)
	ROL_ZEROPAGE			= 0x26,
	ROL_ZEROPAGE_X			= 0x36,
	ROL_ABSOLUTE			= 0x2E,
	ROL_ABSOLUTE_X			= 0x3E,
	ROR_ACCUMULATOR 		= 0x6A,	//Rotate One Bit Right (Memory or Accumulator)
	ROR_ZEROPAGE			= 0x66,
	ROR_ZEROPAGE_X			= 0x76,
	ROR_ABSOLUTE			= 0x6E,
	ROR_ABSOLUTE_X			= 0x7E,
	RTI 					= 0x40,	//Return from Interrupt
	RTS 					= 0x60,	//Return from Subroutine
	SBC_IMMEDIATE 			= 0xE9,	//Subtract Memory from Accumulator with Borrow
	SBC_ZEROPAGE			= 0xE5,
	SBC_ZEROPAGE_X			= 0xF5,
	SBC_ABSOLUTE			= 0xED,
	SBC_ABSOLUTE_X			= 0xFD,
	SBC_ABSOLUTE_Y			= 0xF9,
	SBC_PREINDEXED_INDIRECT	= 0xE1,
	SBC_POSTINDEXED_INDIRECT= 0xF1,
	SEC 					= 0x38,	//Set Carry Flag
	SED 					= 0xF8,	//Set Decimal Mode
	SEI 					= 0x78,	//Set Interrupt Disable Status
	STA_ZEROPAGE 			= 0x85,	//Store Accumulator in Memory
	STA_ZEROPAGE_X			= 0x95,
	STA_ABSOLUTE			= 0x8D,
	STA_ABSOLUTE_X			= 0x9D,
	STA_ABSOLUTE_Y			= 0x99,
	STA_PREINDEXED_INDIRECT	= 0x81,
	STA_POSTINDEXED_INDIRECT= 0x91,
	STX_ZEROPAGE 			= 0x86,	//Store Index X in Memory
	STX_ZEROPAGE_Y			= 0x96,
	STX_ABSOLUTE			= 0x8E,
	STY_ZEROPAGE 			= 0x84,	//Store Index Y in Memory
	STY_ZEROPAGE_X			= 0x94,
	STY_ABSOLUTE			= 0x8C,
	TAX 					= 0xAA,	//Transfer Accumulator to Index X
	TAY 					= 0xA8,	//Transfer Accumulator to Index Y
	TSX 					= 0xBA,	//Transfer Stack Pointer to Index X
	TXA 					= 0x8A,	//Transfer Index X to Accumulator
	TXS 					= 0x9A,	//Transfer Index X to Stack Pointer
	TYA 					= 0x98,	//Transfer Index Y to Accumulator
}

