enum Opcodes6502
{
	ADC_IMMEDIATE			= 0x69,	//Add Memory to Accumulator with Carry
	ADC_ZEROPAGE			= 0x65,
	ADC_ZEROPAGE_X			= 0x75,
	ADC_ABSOLUTE_X			= 0x7D,
	ADC_ABSOLUTE_Y			= 0x79,
	ADC_PREINDEXED_INDIRECT	= 0x61,
	ADC_POSTINDEXED_INDIRECT= 0x71,
	AND_IMMEDIATE			= 0x29,	//"AND" Memory with Accumulator
	AND_ZEROPAGE			= 0x25,
	AND_ZEROPAGE_X			= 0x35,
	AND_ABSOLUTE			= 0x2D,
	AND_ABSOLUTE_X			= 0x3D,
	AND_ABSOLUTE_Y			= 0x39,
	AND_PREINDEXED_INDIRECT	= 0x21,
	AND_POSTINDEXED_INDIRECT= 0x31,
	ASL_ACCUMULATOR		= 0x0A,	//Shift Left One Bit (Memory or Accumulator)
	ASL_ZEROPAGE		= 0x06,
	ASL_ZEROPAGE_X		= 0x16,
	ASL_ABSOLUTE		= 0x0E,
	ASL_ABSOLUTE_X		= 0x1E,
	BCC 				= 0x90,	//Branch on Carry Clear
	BCS 				= 0xB0,	//Branch on Carry Set
	BEQ 				= 0xF0,	//Branch on Result Zero
	BIT_ZEROPAGE		= 0x24,	//Test Bits in Memory with Accumulator
	BIT_ABSOLUTE		= 0x2C,
	BMI 				= 0x30,	//Branch on Result Minus
	BNE 				= 0xD0,	//Branch on Result not Zero
	BPL 				= 0x10,	//Branch on Result Plus
	BRK 				= 0x00,	//Force Break
	BVC 				= 0x50,	//Branch on Overflow Clear
	BVS 				= 0x70,	//Branch on Overflow Set
	CLC 				= 0x18,	//Clear Carry Flag
	CLD 				= 0xD8,	//Clear Decimal Mode
	CLI 				= 0x58,	//Clear interrupt Disable Bit
	CLV 				= 0xB8,	//Clear Overflow Flag
	CMP_IMMEDIATE			= 0xC9,	//Compare Memory and Accumulator
	CMP_ZEROPAGE			= 0xC5,
	CMP_ZEROPAGE_X			= 0xD5,
	CMP_ABSOLUTE			= 0xCD,
	CMP_ABSOLUTE_X			= 0xDD,
	CMP_ABSOLUTE_Y			= 0xD9,
	CMP_PREINDEXED_INDIRECT	= 0xC1,
	CMP_POSTINDEXED_INDIRECT= 0xD1,
	CPX_IMMEDIATE		= 0xE0,	//Compare Memory and Index X
	CPX_ZEROPAGE		= 0xE4,
	CPX_ABSOLUTE 		= 0xEC,
	CPY_IMMEDIATE		= 0xC0,	//Compare Memory and Index Y
	CPY_ZEROPAGE		= 0xC4,
	CPY_ABSOLUTE		= 0xCC,
	DEC_ZEROPAGE		= 0xC6,	//Decrement Memory by One
	DEC_ZEROPAGE_X		= 0xD6,
	DEC_ABSOLUTE		= 0xCE,
	DEC_ABSOLUTE_X		= 0xDE,
	DEX					= 0xCA,	//Decrement Index X by One
	DEY					= 0x88,	//Decrement Index Y by One
	EOR_IMMEDIATE			 = ,	//"Exclusive-Or" Memory with Accumulator
	EOR_ZEROPAGE			 = ,
	EOR_ZEROPAGE_X			 = ,
	EOR_ABSOLUTE			 = ,
	EOR_ABSOLUTE_X			 = ,
	EOR_ABSOLUTE_Y			 = ,
	EOR_PREINDEXED_INDIRECT	 = ,
	EOR_POSTINDEXED_INDIRECT = ,
	INC = ,	//Increment Memory by One
	INX = ,	//Increment Index X by One
	INY = ,	//Increment Index Y by One
	JMP = ,	//Jump to New Location
	JSR = ,	//Jump to New Location Saving Return Address
	LDA = ,	//Load Accumulator with Memory
	LDX = ,	//Load Index X with Memory
	LDY = ,	//Load Index Y with Memory
	LSR = ,	//Shift Right One Bit (Memory or Accumulator)
	NOP = ,	//No Operation
	ORA = ,	//"OR" Memory with Accumulator
	PHA = ,	//Push Accumulator on Stack
	PHP = ,	//Push Processor Status on Stack
	PLA = ,	//Pull Accumulator from Stack
	PLP = ,	//Pull Processor Status from Stack
	ROL = ,	//Rotate One Bit Left (Memory or Accumulator)
	ROR = ,	//Rotate One Bit Right (Memory or Accumulator)
	RTI = ,	//Return from Interrupt
	RTS = ,	//Return from Subroutine
	SBC = ,	//Subtract Memory from Accumulator with Borrow
	SEC = ,	//Set Carry Flag
	SED = ,	//Set Decimal Mode
	SEI = ,	//Set Interrupt Disable Status
	STA = ,	//Store Accumulator in Memory
	STX = ,	//Store Index X in Memory
	STY = ,	//Store Index Y in Memory
	TAX = ,	//Transfer Accumulator to Index X
	TAY = ,	//Transfer Accumulator to Index Y
	TSX = ,	//Transfer Stack Pointer to Index X
	TXA = ,	//Transfer Index X to Accumulator
	TXS = ,	//Transfer Index X to Stack Pointer
	TYA = ,	//Transfer Index Y to Accumulator
}

