#define INVALID_OPCODE_MNEMONIC "UNK"

struct OpcodeInfo
{
	const char* m_mnemonic;		///< three character symbol for this instruction
	unsigned m_numBytes;		///< number of bytes consumed by this instruction, including the opcode byte
	unsigned m_numCycles;		///< base number of cycles that the execution of this opcodes takes 
};

static OpcodeInfo s_opcodesInfo[] =
{
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//00
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "PHP", 1, 3 },
	{ "ORA", 2, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//0A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//0F
	{ "BPL", 2, 2 },						//10
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "CLC", 1, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//1A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//1F
	{ "JSR", 3, 6 },						//20
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "BIT", 2, 3 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "PLP", 1, 4 },
	{ "AND", 2, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//2A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//2F
	{ "BMI", 2, 2 },						//30
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "SEC", 1, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//3A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//3F
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//40
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "PHA", 1, 3 },
	{ "EOR", 2, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//4A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "JMP", 3, 3 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//4F
	{ "BVC", 2, 2 },						//50
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//5A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//5F
	{ "RTS", 1, 6 },						//60
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "PLA", 1, 4 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//6A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//6F
	{ "BVS", 2, 2 },						//70
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "SEI", 1, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//7A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//7F
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//80
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "STA", 2, 3 },
	{ "STX", 2, 3 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//8A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//8F
	{ "BCC", 2, 2 },						//90
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//9A
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//9F
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//A0
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "LDX", 2, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "LDA", 2, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//AA
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//AF
	{ "BCS", 2, 2 },						//B0
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "CLV", 1, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//BA
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//BF
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//C0
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "CMP", 2, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//CA
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//CF
	{ "BNE", 2, 2 },						//D0
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "CLD", 1, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//DA
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//DF
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//E0
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "NOP", 1, 2 },						//EA
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//EF
	{ "BEQ", 2, 2 },						//F0
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ "SED", 1, 2 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },		//FA
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 },
	{ INVALID_OPCODE_MNEMONIC, 1, 1 }		//FF
};
